name: Update matchups

on:
  schedule:
    - cron: '0 0 */2 * *' # A cada 2 dias
  workflow_dispatch:
    inputs:
      person:
        description: 'who uploaded'
        required: false
        default: 'gabriel-gn'

jobs:

  update-matchup-assets:
    name: Auto Update Matchup Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        working-directory: ./
        run: |
          echo "*** Iniciando NPM Install ***"
          npm install
      - name: Update MATCHUP assets
        working-directory: ./
        run: |
          node ./scripts/update-matchups.js
        env:
          PATCH: ${{ github.event.inputs.patch }}
          APPEND_ONLY: ${{ github.event.inputs.appendOnly }}
      - name: Check if there is any change
        id: get_changes
        run: echo "::set-output name=changed::$(git status --porcelain | wc -l)"
      - name: Commit & Push changes
        if: steps.get_changes.outputs.changed != 0
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: ":robot: auto update matchups"
